import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { Rubik } from "next/font/google";
import "@mantine/core/styles.css";
import { ColorSchemeScript } from "@mantine/core";
import Providers from "@/components/providers";
import { getCurrentLocale } from "@/utils/getLocaleServer";

export const metadata: Metadata = {
  title: "Gaza in Memory",
  description: "Generated by create next app",
};

const rubik = Rubik({
  subsets: ["arabic"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-rubik",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = getCurrentLocale();
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${GeistSans.className} ${rubik.variable}`}>
        <Providers>
          <main className="mx-auto max-w-[1750px]">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
