import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import "@mantine/core/styles.css";
import { ColorSchemeScript } from "@mantine/core";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Gaza in Memory",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={GeistSans.className}>
        <Providers>
          <main className=" max-w-[1750px] mx-auto">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
