import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/app/[locale]/_components/navbar";
import "@mantine/core/styles.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  return (
    <main className=" max-w-[1750px] mx-auto">
      <Navbar locale={locale} />
      {children}
    </main>
  );
}
